services:
  db:
    image: postgres:latest
    env_file:
      - ./.env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - 5438:5432
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'",
        ]
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 5s

volumes:
  db_data:
